import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { classify, READ_FORMATS } from "@/lib/formats";
import { extract, recoverFields } from "./index";
import { extractDocx } from "./docx";
import { extractOdt } from "./odt";
import { extractPdf } from "./pdf";
import { extractRtf } from "./rtf";
import { extractText } from "./text";
import type { Extraction, FlagKind } from "./types";

/**
 * Every assertion here runs against a file in testing/, generated by
 * scripts/tasks.ts (fixtures task). Each fixture is named after the thing it is meant
 * to break, so a failure names the defect on its own.
 */
const FIXTURES = join(process.cwd(), "testing");

const bytes = (rel: string) => new Uint8Array(readFileSync(join(FIXTURES, rel)));
const text = (rel: string) => readFileSync(join(FIXTURES, rel), "utf8");

const has = (e: Extraction, kind: FlagKind) =>
  e.flags.some((f) => f.kind === kind);

/** The person in every fixture. */
const NAME = "Alex Mercer";
const EMAIL = "alex.mercer@example.com";
const PHONE = "+1 415 555 0142";
const ORG = "Northwind Systems";

describe("docx", () => {
  it("recovers a clean styled resume", () => {
    const e = extractDocx(bytes("docx/clean-styled.docx"));
    expect(e.text).toContain(NAME);
    expect(e.text).toContain(EMAIL);
    expect(e.text).toContain(ORG);
    expect(e.depth).toBe("layout");
  });

  it("joins runs that Word split mid-word", () => {
    // The skills paragraph is written as three <w:t> fragments. Joined with
    // anything between them, this reads "Go, PostgreS QL, Kaf ka".
    const e = extractDocx(bytes("docx/clean-styled.docx"));
    expect(e.text).toContain("Go, PostgreSQL, Kafka, Terraform, AWS");
  });

  it("labels styled headings", () => {
    const e = extractDocx(bytes("docx/clean-styled.docx"));
    const headings = e.blocks.filter((b) => b.kind === "heading").map((b) => b.text);
    expect(headings).toContain("Experience");
    expect(headings).toContain("Skills");
  });

  it("reads a layout table row-wise and keeps each date with its job", () => {
    const e = extractDocx(bytes("docx/layout-table.docx"));
    const row0 = e.blocks.filter((b) => b.kind === "cell" && b.row === 0);
    expect(row0.map((b) => b.text)).toEqual([
      "March 2021 — Present",
      "Senior Backend Engineer, Northwind Systems",
    ]);
    expect(has(e, "table")).toBe(true);
  });

  it("finds contact details hidden in a text box", () => {
    const e = extractDocx(bytes("docx/contact-in-textbox.docx"));
    const boxed = e.blocks.filter((b) => b.kind === "textbox").map((b) => b.text);
    expect(boxed).toContain(NAME);
    expect(boxed).toContain(EMAIL);
    expect(has(e, "textbox")).toBe(true);
  });

  it("reads the page header, and says so", () => {
    const e = extractDocx(bytes("docx/clean-styled.docx"));
    const header = e.blocks.find((b) => b.kind === "header");
    expect(header?.text).toContain(EMAIL);
    expect(has(e, "headerContent")).toBe(true);
  });

  it("still extracts a document with no styles at all", () => {
    const e = extractDocx(bytes("docx/unstyled-paragraphs.docx"));
    expect(e.text).toContain(NAME);
    expect(e.text).toContain("EXPERIENCE");
    // No w:pStyle anywhere, so nothing should be claimed as a heading.
    expect(e.blocks.filter((b) => b.kind === "heading")).toHaveLength(0);
  });

  it("refuses a file that is not a zip", () => {
    expect(() => extractDocx(bytes("rejected/word-97.doc"))).toThrow(/damaged/i);
  });

  it("refuses a zip with no document part", () => {
    expect(() => extractDocx(bytes("rejected/apple-pages.pages"))).toThrow(
      /no document part/i,
    );
  });
});

describe("odt", () => {
  it("recovers a clean document", () => {
    const e = extractOdt(bytes("odt/clean-styled.odt"));
    expect(e.text).toContain(NAME);
    expect(e.text).toContain(PHONE);
    expect(
      e.blocks.filter((b) => b.kind === "heading").map((b) => b.text),
    ).toContain("Experience");
  });

  it("keeps table rows together", () => {
    const e = extractOdt(bytes("odt/layout-table.odt"));
    const row1 = e.blocks.filter((b) => b.kind === "cell" && b.row === 1);
    expect(row1.map((b) => b.text)).toEqual([
      "June 2018 — February 2021",
      "Backend Engineer, Bellweather Data",
    ]);
    expect(has(e, "table")).toBe(true);
  });
});

describe("rtf", () => {
  it("recovers a clean document", () => {
    const e = extractRtf(text("rtf/clean.rtf"));
    expect(e.text).toContain(NAME);
    expect(e.text).toContain(EMAIL);
    expect(e.text).toContain("Go, PostgreSQL");
  });

  it("keeps the font table out of the text", () => {
    const e = extractRtf(text("rtf/clean.rtf"));
    expect(e.text).not.toContain("Calibri");
  });

  it("decodes escapes and unicode", () => {
    const e = extractRtf(text("rtf/escapes-and-unicode.rtf"));
    expect(e.text).toContain("Anaïs Renaud");
    expect(e.text).toContain("—");
    expect(e.text).toContain("32%");
    // \\u8212 followed by its ansi fallback must not produce both characters.
    expect(e.text).not.toContain("??");
  });
});

describe("plain text", () => {
  it("reads sections, bullets and contact details", () => {
    const e = extractText(text("txt/clean-sections.txt"), false);
    expect(e.text).toContain(EMAIL);
    expect(
      e.blocks.filter((b) => b.kind === "heading").map((b) => b.text),
    ).toEqual(["EXPERIENCE", "EDUCATION", "SKILLS"]);
    expect(e.blocks.filter((b) => b.kind === "listItem")).toHaveLength(3);
    expect(e.depth).toBe("text");
  });

  it("strips a byte order mark and CRLF endings", () => {
    const e = extractText(text("txt/crlf-with-bom.txt"), false);
    expect(e.blocks[0].text).toBe(NAME);
    expect(e.text).not.toContain("\r");
  });

  it("claims no headings when the file has none", () => {
    const e = extractText(text("txt/unstructured-prose.txt"), false);
    expect(e.blocks.filter((b) => b.kind === "heading")).toHaveLength(0);
    expect(e.text).toContain(EMAIL);
  });
});

describe("markdown", () => {
  it("reads headings and keeps a link target", () => {
    const e = extractText(text("md/clean-sections.md"), true);
    const headings = e.blocks.filter((b) => b.kind === "heading").map((b) => b.text);
    expect(headings).toContain(NAME);
    expect(headings).toContain("Experience");
    expect(e.text).toContain("alexmercer.dev (https://alexmercer.dev)");
    // Emphasis markers must not survive into the recovered text.
    expect(e.text).not.toContain("**");
  });

  it("reads a table row-wise and drops the rule line", () => {
    const e = extractText(text("md/history-in-table.md"), true);
    const row1 = e.blocks.filter((b) => b.kind === "cell" && b.row === 1);
    expect(row1.map((b) => b.text)).toEqual([
      "Senior Backend Engineer",
      ORG,
      "March 2021 — Present",
    ]);
    expect(e.text).not.toContain("---");
    expect(has(e, "table")).toBe(true);
  });
});

/** pdf.js ships a separate build for Node; the browser one wants a worker. */
const nodePdfjs = async () =>
  (await import("pdfjs-dist/legacy/build/pdf.mjs")) as never;

describe("pdf", () => {
  it("recovers a single-column resume in reading order", async () => {
    const e = await extractPdf(bytes("pdf/clean-single-column.pdf"), nodePdfjs);
    expect(e.hasTextLayer).toBe(true);
    expect(e.pages).toBe(1);
    expect(e.blocks[0].text).toBe(NAME);
    expect(e.text).toContain(EMAIL);
    expect(e.text).toContain("EXPERIENCE");
    expect(has(e, "readingOrder")).toBe(false);
    expect(has(e, "multiColumn")).toBe(false);
  });

  it("sizes headings from the type, not the wording", async () => {
    const e = await extractPdf(bytes("pdf/clean-single-column.pdf"), nodePdfjs);
    const headings = e.blocks.filter((b) => b.kind === "heading").map((b) => b.text);
    expect(headings).toContain("EXPERIENCE");
    expect(headings).toContain("SKILLS");
  });

  it("catches a two-column layout and the shuffled order it causes", async () => {
    const e = await extractPdf(bytes("pdf/two-column-layout.pdf"), nodePdfjs);
    expect(has(e, "multiColumn")).toBe(true);
    // The finding stands even though we recover it: most parsers will not.
    expect(e.text).toContain(EMAIL);
    expect(e.text).toContain(ORG);
  });

  /*
   * The layout engine emits a two-column page row by row, so the left
   * column's contact rail and the right column's history share a baseline.
   * Read straight down, every line came out as one column's text glued to
   * the other's: a summary paragraph with a skills list spliced through it.
   */
  it("reads each column to the bottom before starting the next", async () => {
    const e = await extractPdf(bytes("pdf/two-column-layout.pdf"), nodePdfjs);

    // No block may hold text from both columns at once.
    const glued = e.blocks.filter(
      (b) => b.text.includes(EMAIL) && b.text.includes("Senior Backend"),
    );
    expect(glued).toEqual([]);

    // SKILLS sits at the foot of the left rail, EXPERIENCE at the head of the
    // right one. Reading by column puts the whole left rail first.
    expect(e.text.indexOf("SKILLS")).toBeGreaterThan(-1);
    expect(e.text.indexOf("SKILLS")).toBeLessThan(e.text.indexOf("EXPERIENCE"));
  });

  /*
   * A photo is conventional on a resume across much of Europe and Asia and is
   * unreadable everywhere. It used to vanish without a word: the text came
   * through, the picture did not, and nothing said so.
   */
  it("says a Word file holds a picture", () => {
    const e = extractDocx(bytes("docx/photo.docx"));
    expect(has(e, "image")).toBe(true);
    // The text around it still comes through.
    expect(e.text).toContain(NAME);
  });

  it("does not report a picture in a document without one", () => {
    expect(has(extractDocx(bytes("docx/clean-styled.docx")), "image")).toBe(
      false,
    );
  });

  it("does not call a scan a picture as well as a missing text layer", async () => {
    // One defect, one finding: a page that is only an image is already
    // reported as having no text layer.
    const e = await extractPdf(bytes("pdf/no-text-layer.pdf"), nodePdfjs);
    expect(has(e, "noTextLayer")).toBe(true);
    expect(has(e, "image")).toBe(false);
  });

  it("reports a scan as having no text layer", async () => {
    const e = await extractPdf(bytes("pdf/no-text-layer.pdf"), nodePdfjs);
    expect(e.hasTextLayer).toBe(false);
    expect(e.text).toBe("");
    expect(has(e, "noTextLayer")).toBe(true);
  });

  it("reads both pages in order", async () => {
    const e = await extractPdf(bytes("pdf/two-pages.pdf"), nodePdfjs);
    expect(e.pages).toBe(2);
    expect(e.blocks.at(-1)?.page).toBe(2);
    expect(e.text.indexOf("EXPERIENCE")).toBeLessThan(e.text.indexOf("EDUCATION"));
  });

  it("refuses an empty file", async () => {
    await expect(
      extractPdf(bytes("rejected/empty.pdf"), nodePdfjs),
    ).rejects.toThrow(/could not be opened/i);
  });
});

describe("the picker and the readers agree", () => {
  const file = (name: string, size = 1000) =>
    ({ name, size }) as File;

  it("accepts every format that has an extractor", () => {
    for (const ext of [".pdf", ".docx", ".odt", ".rtf", ".txt", ".md"]) {
      expect(classify(file(`resume${ext}`)).ok).toBe(true);
    }
  });

  it("turns away a web page, which no hiring system accepts", () => {
    const html = classify(file("resume.html"));
    expect(html.ok).toBe(false);
    if (!html.ok) expect(html.reason).toMatch(/Print it to PDF/);
  });

  it("names the way out for formats it will not read", () => {
    const doc = classify(file("resume.doc"));
    expect(doc.ok).toBe(false);
    if (!doc.ok) expect(doc.reason).toMatch(/Save As/);

    const pages = classify(file("resume.pages"));
    if (!pages.ok) expect(pages.reason).toMatch(/Export To/);
  });

  it("rejects an empty file and one over the limit", () => {
    expect(classify(file("resume.pdf", 0)).ok).toBe(false);
    expect(classify(file("resume.pdf", 11 * 1024 * 1024)).ok).toBe(false);
  });
});

/*
 * The dispatcher, exercised through real File objects rather than by calling
 * each reader directly. It imports every reader on demand, and a broken
 * dynamic path fails at runtime in the browser and nowhere else, the unit
 * tests above would all still pass.
 */
describe("extract() dispatch", () => {
  const asFile = (rel: string) =>
    new File([readFileSync(join(FIXTURES, rel))], rel.split("/").pop() ?? rel);

  const cases: [string, string][] = [
    ["docx/clean-styled.docx", ".docx"],
    ["odt/clean-styled.odt", ".odt"],
    ["rtf/clean.rtf", ".rtf"],
    ["txt/clean-sections.txt", ".txt"],
    ["md/clean-sections.md", ".md"],
  ];

  it.each(cases)("reads %s and recovers the person", async (path, ext) => {
    const format = READ_FORMATS.find((f) => f.ext === ext);
    if (!format) throw new Error(`no format registered for ${ext}`);

    const result = await extract(asFile(path), format);
    expect(result.text).toContain(NAME);

    const fields = recoverFields(result);
    const byKey = Object.fromEntries(fields.map((f) => [f.key, f.value]));
    expect(byKey.name).toBe(NAME);
    expect(byKey.email).toBeTruthy();
    expect(byKey.phone).toBeTruthy();
    expect(byKey.dates).toContain("range");
  });

  it("recovers fields from a two-column PDF despite the interleaving", async () => {
    const e = await extractPdf(bytes("pdf/two-column-layout.pdf"), nodePdfjs);
    const byKey = Object.fromEntries(
      recoverFields(e).map((f) => [f.key, f.value]),
    );
    expect(byKey.email).toBe(EMAIL);
    expect(byKey.name).toBe(NAME);
  });

  it("finds nothing in a scan, and says so rather than guessing", async () => {
    const e = await extractPdf(bytes("pdf/no-text-layer.pdf"), nodePdfjs);
    const fields = recoverFields(e);
    expect(fields.every((f) => f.value === null)).toBe(true);
    expect(fields.find((f) => f.key === "email")?.lost).toBeTruthy();
  });
});
