/**
 * Writes FORMULA.md: every number the scoring uses, in one reviewable page.
 *
 * Generated rather than written, and read straight out of the modules that do
 * the scoring, so it cannot drift from the code. A hand-maintained copy of a
 * weight table is wrong the first time somebody tunes a number and forgets.
 *
 * The output is gitignored. The weights are the one part of the scoring that is
 * ours rather than borrowed from a citation, and the committed doc
 * (docs/08-scoring.md) describes the method and the sources without the price
 * list.
 *
 * Run: npm run formula
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BAND_FLOOR,
  CEILING,
  FIELD_COSTS,
  FLAG_COSTS,
  OVERSIZE_COST,
  PARSE_SIZE_LIMIT,
  SEVERITY_FLOOR,
  VERDICTS,
} from "../src/extract/score";
import { MAX_TERMS, STOPWORD_COUNT, STUFFING } from "../src/extract/keywords";
import { SPACING_TIERS } from "../src/extract/letterspacing";
import { PLACEHOLDER_COST } from "../src/extract/score";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
/** Sits with the research notes it was derived from. Gitignored, see .gitignore. */
const OUT = join(ROOT, "Score-test", "FORMULA.md");

/** Which severity label a cost lands on. Mirrors severity() in score.ts. */
function severityOf(cost: number): string {
  if (cost >= SEVERITY_FLOOR.blocking) return "Blocking";
  if (cost >= SEVERITY_FLOOR.high) return "Major";
  if (cost >= SEVERITY_FLOOR.medium) return "Moderate";
  return "Minor";
}

type Row = { label: string; cost: number; source: string; detail: string };

const fieldRows: Row[] = Object.entries(FIELD_COSTS).map(([key, v]) => ({
  label: `Missing ${key}`,
  cost: v.cost,
  source: v.basis.source,
  detail: v.detail,
}));

const flagRows: Row[] = Object.entries(FLAG_COSTS).map(([, v]) => ({
  label: v.label,
  cost: v.cost,
  source: v.basis.source,
  detail: "Raised by the extractor when it finds this in the document.",
}));

const sizeRow: Row = {
  label: `Over ${(PARSE_SIZE_LIMIT / 1024 / 1024).toFixed(1)}MB`,
  cost: OVERSIZE_COST,
  source: "Greenhouse Support, supported formats and parse limits",
  detail:
    "Greenhouse stops parsing above this size whatever the upload limit allows, so the file uploads and the record arrives empty.",
};

/** Detectors that produce a finding without living in either cost table. */
const detectorRows: Row[] = [
  {
    label: `${SPACING_TIERS[0].label} (worst tier)`,
    cost: SPACING_TIERS[0].cost,
    source: "Greenhouse Support, Unsuccessful resume parse",
    detail:
      "Runs of four or more single-letter tokens. A parser cannot rejoin the characters, so the text contributes no searchable terms.",
  },
  {
    label: "Unfilled template text",
    cost: PLACEHOLDER_COST,
    source: "Greenhouse Support, Unsuccessful resume parse",
    detail:
      "Greenhouse skips data it reads as placeholder. In practice it usually means a template nobody finished.",
  },
];

const all = [...flagRows, ...fieldRows, ...detectorRows, sizeRow].sort(
  (a, b) => b.cost - a.cost,
);

const fatal = all.filter((r) => r.cost >= SEVERITY_FLOOR.blocking);
const scored = all.filter((r) => r.cost < SEVERITY_FLOOR.blocking);

/** Deduplicated citations across every weight. */
const sources = [
  ...new Set(
    [...Object.values(FIELD_COSTS), ...Object.values(FLAG_COSTS)].map(
      (v) => `${v.basis.source}\n  <${v.basis.url}>\n  ${v.basis.claim}`,
    ),
  ),
];

const md = `# Scoring formula

Generated by \`npm run formula\` from \`src/extract/score.ts\` and
\`src/extract/keywords.ts\`. Not in version control: see .gitignore. Do not edit
this file, edit the code and regenerate.

## Shape

\`\`\`text
score = ${CEILING} × Π (1 - cost/100)      for every finding
\`\`\`

Multiplicative, not subtractive. Each cost is a **percentage of the remaining
score**, so a finding takes more off a clean document than off a wrecked one.
The old \`${CEILING} - sum(costs)\` had two problems: the costs summed to well
past ${CEILING}, so the top of the range did nothing, and anything past the
ceiling clipped to 0, which meant a real fix could move the score from 0 to 0.
Multiplying cannot go below zero, so nothing clips and every fix moves the
number.

The unit changed with the aggregate. A cost of 18 used to remove 18 points; now
it removes 18% of what is left. Ordering is unchanged, so the severity labels
still rank correctly.

The ceiling is ${CEILING}, not 100. No vendor publishes its parser rules, so a
perfect score would be a claim about software nobody outside those companies can
inspect.

## Fatal

These cost 100, so their factor is zero and the score reaches zero through the
same arithmetic as everything else. No short-circuit and no special case.

${fatal.map((r) => `- **${r.label}** (${r.cost})`).join("\n")}
- Empty extracted text, whatever the reason and whether or not a flag was raised

## Blockers, held outside the score

Not gradual, so they are neither multiplied in nor treated as fatal. A file the
portal will not accept never reaches a parser, so a number describing how well
it would have parsed is beside the point. Shown above the score; the score still
computes, because the content advice survives the re-export.

- **Format not accepted.** Greenhouse takes .pdf, .docx, .rtf and .txt. It does
  not take .odt or .md, both of which we can read and neither of which we should
  let somebody submit believing they scored 95.

## Scored findings

Sorted heaviest first, which is also the order the UI lists them in.

| Finding | Cost | Shown as | Rests on |
| --- | --- | --- | --- |
${scored
  .map((r) => `| ${r.label} | ${r.cost} | ${severityOf(r.cost)} | ${r.source} |`)
  .join("\n")}

Every one of these firing at once leaves ${Math.round(
  scored.reduce((acc, r) => acc * (1 - r.cost / 100), CEILING),
)}, reached by multiplication rather
than by clipping.

Letter-spaced text is tiered by how much of the document it covers
(${SPACING_TIERS.map((t) => t.cost).join(" / ")}), because a spaced-out heading and a spaced-out
resume are not the same problem.

## Severity labels

The UI shows these instead of the costs. Same ordering, no price list.

| Label | Cost at or above |
| --- | --- |
${Object.entries(SEVERITY_FLOOR)
  .map(([k, v]) => `| ${severityOf(v)} | ${v} |`)
  .join("\n")}

## Bands and verdicts

| Band | Score at or above | Verdict shown |
| --- | --- | --- |
${(Object.keys(BAND_FLOOR) as (keyof typeof BAND_FLOOR)[])
  .map((b) => `| ${b} | ${BAND_FLOOR[b]} | ${VERDICTS[b]} |`)
  .join("\n")}

## Skipped checks

A format that cannot fail a check has it listed as not scored, never as passed.

| Format depth | Not scored |
| --- | --- |
| layout (PDF, .docx, .odt) | nothing, every check applies |
| markup (.rtf) | reading order, column layout, text layer |
| text (.txt, .md) | reading order, column layout, text layer, tables |

## Keyword matching

Separate from the score and never folded into it. A resume is not worse for
failing to match a posting the person has not applied to.

- Terms reported: top ${MAX_TERMS}, ranked by how often the posting asks, then by phrase length
- Single words and two-word phrases; both halves of a phrase must carry signal
- Stopword list: ${STOPWORD_COUNT()} entries, ordinary English plus recruiting boilerplate
- Stuffing flagged when a term appears more than ${STUFFING.timesInResume} times in the resume **and** more than ${STUFFING.timesAsked}x what the posting asks
- Coverage is reported as "n of m terms", never as a percentage score
- Abbreviations are expanded in both directions and reported as **near misses**,
  never counted as matches. The screening systems match literal text, so scoring
  \`K8s\` as \`Kubernetes\` would flatter the figure with a match they will not
  make. Ambiguous ones (\`PM\`, \`CS\`, \`SA\`) surface every reading and pick none.

## Every citation

${sources.map((s) => `- ${s}`).join("\n")}

## Judgement calls, not citations

These are the numbers to argue with:

- The exact boundary between Major and Moderate (${SEVERITY_FLOOR.high} and ${SEVERITY_FLOOR.medium})
- ${OVERSIZE_COST} for oversize. Greenhouse stops *parsing* at 2.5MB but accepts uploads
  to 100MB, so the file attaches and a recruiter re-keys it. Auto-fill fails,
  nobody is rejected. This was 30, which overstated it.
- 28 for column layout and reading order merged. 22 was the higher of the two
  costs it replaces, plus a margin because columns also confuse section
  boundaries. The two used to bill separately, 42 points for one defect.
- ${SPACING_TIERS.map((t) => t.cost).join(" / ")} for the letter-spacing tiers, and the 20% / 5% boundaries between them
- ${PLACEHOLDER_COST} for unfilled template text, priced as a lost employer name
- The band boundaries (${BAND_FLOOR.clean} / ${BAND_FLOOR.minor} / ${BAND_FLOOR.risky}). Set by what each band should mean, not
  measured. The only corpus is the fixtures in testing/, which were built to
  exercise detectors rather than to represent real resumes, so reading
  boundaries off their distribution would be measurement theatre.

Everything else traces to a source in the list above.

## Not implemented, on purpose

Symptom suppression, where a text box or page header would zero the missing
contact fields it explains, was specified and rejected. On DOCX and ODT we read
text box, header and footer contents into the main text, so a trapped email is
found and \`Missing email\` never fires alongside \`Text box\`. The two only
co-occur when the email is genuinely absent, which is exactly when suppressing
it would be wrong. PDF has no text-box detector at all yet, which is the real
gap the proposal found while looking somewhere else.
`;

writeFileSync(OUT, md);
console.log(
  `FORMULA.md  ${scored.length + fatal.length} weights, ${sources.length} citations`,
);
